name: Check format

on: push

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: jdx/mise-action@v4

      - name: Check format
        run: mise run fmt:check
