on:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write

name: release-artifact

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v10
        with:
          lua-version: 5.4

      - name: Build
        run: make build

      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref }} ./dist/neblua.lua
          gh release upload ${{ github.ref }} ./dist/neblua-cli.lua
